### ISSUE TITLE
Scroll on Modal

### ISSUE THREAD

**Issue by Seb-** [base-apps/angular-base-apps#70]
What is the status of having scroll bar inside modals?

I tried with 1.2.6: I have a modal that is too big (vertically) for the window and I would like it to have a scroll bar, but it doesn't seem to work.

What is the best solution for this?

**Comment by soumak77** [comment]
I use the following SCSS to achieve this:

``` scss
.modal-overlay {
  .modal {
    overflow: auto;
    -webkit-overflow-scrolling: touch;
  }
}
```

**Comment by soumak77** [comment]
Or if you want your modal to contain a grid:

``` scss
aside {
  display: flex;
}
```
